# For help completing this file, see the "AppSpec File Reference" in the
#   "CodeDeploy User Guide" at
#   https://docs.aws.amazon.com/codedeploy/latest/userguide/app-spec-ref.html
version: 0.0

os: linux

# During the Install deployment lifecycle event (which occurs between the
#   BeforeInstall and AfterInstall events), copy the specified files
#   in "source" starting from the root of the revision's file bundle
#   to "destination" on the Amazon EC2 instance.
# Specify multiple "source" and "destination" pairs if you want to copy
#   from multiple sources or to multiple destinations.
files:
  - source: .
    destination: /var/www/drupal/drupal-github-aws-ci-cd-testing
file_exists_behavior: OVERWRITE

hooks:
  BeforeInstall:
    - location: .aws/scripts/before-install.sh
      runas: root
  AfterInstall:
    - location: .aws/scripts/after-install.sh
      runas: root
