version: "3.8"
name: sonarqube-apache-postgres-stack
services:

  apache:
    container_name: apache
    image: httpd:2.4
    restart: always
    depends_on:
      - sonarqube
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./sonarqube.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
      - httpd_logs:/usr/local/apache2/logs
    networks:
      - sonarnet

  sonarqube:
    container_name: sonarqube
    image: sonarqube:latest
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: true
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    depends_on:
      - db
    volumes:
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled_plugins:/opt/sonarqube/lib/bundled-plugins
    networks:
      - sonarnet

  db:
    container_name: postgres
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - sonarnet

volumes:
  httpd_logs:
  sonarqube_logs:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled_plugins:
  postgresql:
  postgresql_data:

networks:
  sonarnet:
